-- Enforce RLS policies for table owners with FORCE ROW LEVEL SECURITY

ALTER TABLE "public"."Theme" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."Bio" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."ContactInfo" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."Member" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."Show" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."Video" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."FeaturedVideo" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."FeaturedRelease" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."MediaImage" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."HomeImage" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."MerchConfig" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."ShowsSettings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "public"."SpotifyPlayer" FORCE ROW LEVEL SECURITY;


