name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS apps
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            set -e

            #
            # Ensure ownership so Git can write FETCH_HEAD
            #
            sudo chown -R $USER:$USER /var/www/logans-run.com/html/logans_run-site
            sudo chown -R $USER:$USER /var/www/yesdevil.com/html/logans_run-site

            for SITE_DIR in \
              /var/www/logans-run.com/html/logans_run-site \
              /var/www/yesdevil.com/html/logans_run-site
            do
              echo "→ Processing ${SITE_DIR}"
              cd "${SITE_DIR}"

              # 1) Make sure Git trusts this directory
              git config --global --add safe.directory "${SITE_DIR}"

              # 2) Point “origin” at your single repo
              git remote set-url origin git@github.com:logan-barsell/logans_run-site.git

              # 3) Fetch & reset to ensure a clean slate
              git fetch origin main
              git reset --hard origin/main

              # 4) Install and build
              npm install
              cd client
              sudo rm -rf build
              npm install
              npm run build

              # back out to parent for next iteration
              cd ../../
            done

            #
            # Restart your services
            #
            echo "→ Restarting nginx"
            sudo systemctl restart nginx

            echo "→ Reloading PM2 processes"
            pm2 reload logans-run
            pm2 reload yesdevil
