name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS apps
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            set -e

            ######################################
            # 0) Fix any ownership issues
            ######################################
            echo "→ Ensuring both repos are owned by $USER"
            sudo chown -R $USER:$USER /var/www/logans-run.com/html/logans_run-site
            sudo chown -R $USER:$USER /var/www/yesdevil.com/html/logans_run-site

            ######################################
            # 1) Update Logans-Run site
            ######################################
            echo "→ Marking Logans-Run as safe"
            git config --global --add safe.directory /var/www/logans-run.com/html/logans_run-site

            echo "→ Updating logans_run-site"
            cd /var/www/logans-run.com/html/logans_run-site
            git pull origin main
            npm install
            cd client
            sudo rm -rf build
            npm install
            npm run build

            ######################################
            # 2) Update YesDevil site
            ######################################
            echo "→ Marking YesDevil as safe"
            git config --global --add safe.directory /var/www/yesdevil.com/html/logans_run-site

            echo "→ Updating yesdevil logans_run-site"
            cd /var/www/yesdevil.com/html/logans_run-site
            git pull origin main
            npm install
            cd client
            sudo rm -rf build
            npm install
            npm run build

            ######################################
            # 3) Restart your services
            ######################################
            echo "→ Restarting nginx & pm2"
            sudo systemctl restart nginx
            pm2 reload logans-run
            pm2 reload yesdevil
