name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS apps
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          forward_agent: true

          script: |
            set -e

            echo "→ Updating Logans Run"
            cd /var/www/logans-run.com/html/logans_run-site
            git pull
            npm install
            cd client
            npm install
            npm run build

            echo "→ Updating YesDevil"
            cd /var/www/yesdevil.com/html/logans_run-site
            git pull
            npm install
            cd client
            npm install
            npm run build

            echo "→ Restarting services"
            sudo systemctl restart nginx
            pm2 reload logans-run
            pm2 reload yesdevil
