name: Test SSH key and connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Write deploy key and test SSH login
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # write the key to a temp file
          echo "$SSH_KEY" > ./tmp_id_rsa
          chmod 600 ./tmp_id_rsa

          # test SSH handshake
          ssh -i ./tmp_id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            'echo "✅ SSH login succeeded"'
